### ISSUE TITLE
Add a `.odc.explore()` method for automatically plotting raster data on an interactive map

### ISSUE THREAD

**Issue by robbibt** [opendatacube/odc-geo#104]
Geopandas recently added an extremely useful `.explore()` method that allows users to quickly plot and inspect data on an interactive map: https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.explore.html

Being able to quickly plot and inspect raster data on an interactive map would be incredibly useful, and would avoid a common workflow of having to export to GeoTIFF and load data into a GIS just to inspect it closely.

Luckily with `odc-geo` we can already do something like this:
```
import folium
import rioxarray
import odc.geo.xr 

ds = rioxarray.open_rasterio(
    "https://dea-public-data-dev.s3-ap-southeast-2.amazonaws.com/derivative/dea_intertidal/sample_data/160/2019-2021/DEV_160_2019_2021_elevation.tif",
    masked=True,
).squeeze("band")

# Create folium Map
m = folium.Map()

# Reproject to 3857
ds_reproj = ds.odc.reproject("epsg:3857")

# Add to map
ds_reproj.odc.add_to(m)

# Zoom map to bounds
m.fit_bounds(ds.odc.map_bounds())
display(m)
```

But this adds a lot of boilerplate code that makes this harder than it needs to be.

**Proposal**
Instead, we could add a new `.odc.explore()` method to `odc-geo` that mimics the `.explore()` functionality of Geopandas. In my mind, calling `ds.odc.explore()` would automatically:
- Create a Folium or Ipyleaflet map
- Reproject data to "epsg:3857"
- Add the reprojected data to the map 
- Fit the map bounds to the data
- Display the map

I'd be keen to have a go at adding something like this, but I'd love to know if there's any obvious issues with this proposal. One thing I can think of is that neither `folium` or `ipyleaflet` are currently included as a requirement for `odc-geo` (I imagine to keep it as small and manageable as possible), so this may be a blocker to adding a feature that depends on those packages?

**Comment by Kirill888** [comment]
Something like this is certainly needed, but I want to be able to combine several `odc-geo` elements together, ideally with some kind of config option available.

I was experimenting with syntax like this:

```python
aa = odc.stac.load(...)
bb = aa.odc.reproject(3857)

aa.odc.geobox >> bb.odc.geobox%{'color': 'red'} >> bb.odc.preview | folium.Map()
```
