### ISSUE TITLE
negative size shape is allowed

### ISSUE THREAD

**Issue by mdsumner** [opendatacube/odc-geo#136]
I noticed that values of `shape` can be negative, this doesn't seem desirable, it has the effect of flipping the transform as expected. 

```python
from odc.geo.geobox import GeoBox
ex = [-120, -100, 35, 55]

g = GeoBox.from_bbox([140, -43, 160, -23],
   "EPSG:4326", 
   shape = [-1, 1])
g
#GeoBox((-1, 1), Affine(20.0, 0.0, 140.0,
#       0.0, 20.0, -60.0), CRS('EPSG:4326'))
```

I only noticed because I wanted to do the GDAL thing of setting one of the dimensions to zero, whereby you only need to use the shape of one side and it helpfully calculates the other from the aspect ratio of the extent. This is nice because it gives a very short heuristic for "about this detailed" that matches how images work, rather than having  to specify a specific resolution or do gymnastics to work out the ratio.   

So, maybe negative shape should be disallowed, and if it's of interest I could PR the `shape = [0, n]` or `shape = [n, 0]`. 

Thanks!

**Comment by Kirill888** [comment]
Thanks Michael, we should probably raise `ValueError` on such inputs, PR is welcome. `0` should be allowed though, I would not clip to `0` however, raise an error when negative dimensions are requested, or whatever `numpy.zeros` would do in such case , which is `ValueError: negative dimensions are not allowed`.

**Comment by mdsumner** [comment]
sorry, is that typo about allowing 0?

I can't tell if you mean

- allow 0 (for infinitely thin or infinitely short y- x- intervals), you wouldn't want a 0,0 geobox I'm assuming 
- disallow 0
- allow 0 for one of rows/columns, which expands to a normal non-zero based on the  non-zero value (for auto-aspect aware dimension-ing so the user doesn't have to do gymnastics to determine the right complementary value)

or something else I'm not understanding (?)

**Comment by Kirill888** [comment]
0 is ok, less than 0 is not

**Comment by mdsumner** [comment]
I was just getting into this ... thanks!  haha
