### ISSUE TITLE
Use of newer type hinting syntax breaks for Python < 3.10

### ISSUE THREAD

**Issue by fbunt** [opendatacube/odc-geo#153]
A recent commit (3b146cbd55279d4ba13930679a53dbbc167b1010) added a function that uses the newer type hinting syntax, specifically the bar (|) operator. This breaks for versions of Python < 3.10. The line that breaks is [here](https://github.com/opendatacube/odc-geo/blame/72e873ad49fe73ad6a9349f9853003dbcb21e181/odc/geo/cog/_rio.py#L87C3-L87C3). `Union` can be used instead to allow backward compatibility.

**Comment by Kirill888** [comment]
Missing from future import.

We should convert typing to new style throughout the codebase. There is probably a tool for that.

**Comment by Kirill888** [comment]
The tools is: `pyupgrade`

https://github.com/asottile/pyupgrade?tab=readme-ov-file#pep-604-typing-rewrites

@SpacemanPaul have you ever tried this one on `datacube` code?

**Comment by SpacemanPaul** [comment]
No I haven't - will check it out.

**Comment by fbunt** [comment]
Is it possible to push a new release with the fix? This is still an issue
