### ISSUE TITLE
ENH: _res support for initialization from a tuple of size 2

### ISSUE THREAD

**Issue by snowman2** [opendatacube/odc-geo#20]
https://github.com/opendatacube/odc-geo/blob/159ae64a973f322736b56633701647388ccffdf7/odc/geo/types.py#L279

Currently get this error: `ValueError: Unsupported input type: res_(x: <class 'tuple'>)`

**Comment by Kirill888** [comment]
that's by design. thinking here is that order of resolution within a tuple is ambiguous, is it `x,y` is it `y,x`, you are supposed to use `resyx_/resxy_` instead.

**Comment by Kirill888** [comment]
Within datacube code itself resolution was mostly supplied in `y,x` order, but I can not 100% confirm that. So maybe it's worthwhile having a separate "datacube compatibility" version of that function, but behavior of `res_` itself won't change from the current one.

**Comment by snowman2** [comment]
Sounds good, thanks :+1:
