### ISSUE TITLE
BUG: Shape/Bounds different with odc-geo compared to datacube

### ISSUE THREAD

**Issue by snowman2** [opendatacube/odc-geo#22]
Currently testing transitioning from datacube to odc-geo in geocube: https://github.com/corteva/geocube/pull/95

Have some scenarios in the tests where the shape is off by one:
odc-geo: (y: 100001, x: 11)
datacube: (y: 100001, x: 12)

And the boundary differs:
odc-geo: [1665945., 7018509., 1665478., 7018306.]
datacube: [1665478., 7018306., 1665945., 7018509.]

Are these changes expected?

**Comment by Kirill888** [comment]
Is there projection change in there somewhere? Behaviour of `.to_crs` [changed](https://odc-geo.readthedocs.io/en/latest/migration.html#to-crs), it no longer adds extra points by default as it's tricky to decide what is a good "precision" for the transform.

**Comment by Kirill888** [comment]
@snowman2 you should be able to get previous behavior with something like this
```python
def _default_reproject_resolution(geom):
    return 1 if geom.crs.geographic else 100_000

geom.to_crs(dst_crs, resolution=_default_reproject_resolution(geom))
```

**Comment by snowman2** [comment]
Thanks @Kirill888 :+1:

**Comment by snowman2** [comment]
Seems that this isn't an issue after all. After applying your suggestions in https://github.com/corteva/geocube/pull/95, the issue has gone away.

**Comment by Kirill888** [comment]
> Seems that this isn't an issue after all. After applying your suggestions in https://github.com/corteva/geocube/pull/95, the issue has gone away.

@snowman2 I guess this was transposition of resolution parameter from expected `y,x` to `x,y` that triggered those tests to fail then.

**Comment by snowman2** [comment]
Yes, that sounds correct. Thanks again 👍
