### ISSUE TITLE
Support generic affine in xarray rasters

### ISSUE THREAD

**Issue by Kirill888** [opendatacube/odc-geo#28]
## Motivation

Code in `xx.odc.geobox` assumes that xarray raster data is axis aligned. That is the off-diagonal terms of the affine matrix are zero and so entire row of pixels will have the same Y coordinate and similarly entire column same X coordinate:

|y\x|0|1|2|3|
|-|-|-|-|-|
|**0**|0,0|1,0|2,0|3,0|
|**1**|0,1|1,1|2,1|3,1|

This limitation means one can not use `.odc.geobox` on rotated images. For a lot of satellite data one swatch of observation happens on an angle, when this gets rendered into axis aligned image you end up with a large proportion of the mosaic image being empty. Supporting arbitrary affine transform could make it much easier to work with large scale mosaics for such data sources.

### 2-d axis

Xarray supports 2d coordinate, so one could simply compute X,Y coordinate for every pixel and store that in two 2d arrays, one for X and one for Y.

``` python
pix = img[r,c]
coord = (img.x[c], img.y[r])  # axis aligned representation
...
coord = (img.x[r,c], img.y[r,c]) # 2d-axis representation
```

 `.odc.geobox` could then detect that 2d axis are used and reconstruct affine matrix from coordinates similar to current implementation but it will need to be computed from 3 points (Affine matrix has 6 degrees of freedom).

- :-1: Significant memory overhead (2 float32 values per pixel, so 8 bytes per pixel)
- :-1: This representation demands axis being Dask arrays as well.
- :+1: Same representation can be used for completely non-linear pixel to world mapping as well
- :+1: Direct support for plotting from xarray itself

### Pixel coords + Affine matrix in attributes

In this scheme we keep 1-d X,Y axis, but they contain pixel coordinates and not real world coordinates, so `x = [0.5, 1.5, 2.5... W-0.5]`, that sort of thing. We then also need to store actual affine matrix in some attributes attached to `x,y` axis. 

In this scenario `.odc.geobox` needs to detect the fact that `X,Y` axis contain pixel coordinates rather than real world coordinates and instead extract affine matrix from attributes/encoding. Slicing should still work as we will have access to the original image coordinates which is what we need to compute world coordinates from. Need to experiment with the location and representation for affine matrix data and how that works with things like `.to_netcdf|to_zarr`.

- affine format: 6 float values (string vs array vs dict)
- attachment point: `x,y` axis vs `crs` axis vs `band`

- :+1: Same memory requirements as axis aligned representation
- :-1: xarray plotting won't display more than one dataset on the same axis properly

**Comment by Kirill888** [comment]
@snowman2 any thoughts on this one?

**Comment by snowman2** [comment]
Related:
- https://github.com/corteva/rioxarray/pull/401
- https://github.com/corteva/rioxarray/pull/292

**Comment by snowman2** [comment]
Potentially useful: https://corteva.github.io/rioxarray/stable/rioxarray.html#rioxarray.rioxarray.XRasterBase.write_transform

**Comment by Kirill888** [comment]
After some thinking about it I tend to lean towards implementing second option first: pixel coords at load/create time + affine matrix stored in `encoding` dict of x/y coords.

 `.odc.geobox` accessor will then detect the fact that x/y coordinates contain original pixel coordinate values and not CRS coordinates, it will compute pixel-level transform relative to the original, in case there was cropping, and then convert it to transform that maps `pix->crs`.

Writing to TIFF should work without any modification, same goes for reproject logic. Writing to netcdf won't produce correct result as x/y coordinate values won't be correct. We could then implement converter that will expand x,y pix coords + transform to 2d x,y to support netcdf output.

**Comment by Kirill888** [comment]
This is now half-done, there is a new mode that places *original pixel coordinates* into 1-d x,y axis and also records transform from those to CRS coordinates in the encoding dict of both x,y axis. `pix.odc.geobox` is aware of that mode and computes correct transform to CRS space. No changes were needed to cog output, reproject and rasterize code to support xarrays with non-axis-aligned geoboxes.

Next step is to support 2-d X,Y axis for situations where plotting against actual coordinates is desired.

**Comment by Kirill888** [comment]
After some thought, I feel like the current approach of storing original pixel coordinates in `x,y` axis with pixel to world transform captured in attributes is good enough. And the same mechanism worked to enable GCP GeoBox as well.
