### ISSUE TITLE
Add a `snap_to` method to GeoBoxes to enable coercing GeoBoxes to the same pixel alignment

### ISSUE THREAD

**Issue by robbibt** [opendatacube/odc-geo#59]
I have two low-resolution GeoBoxes created by "zooming out" of two existing higher resolution dataset GeoBoxes:
```
lowres_geobox1 = ds1.odc.geobox.zoom_out(500)
lowres_geobox2 = ds2.odc.geobox.zoom_out(500)
```

Although these GeoBoxes share the same resolution and CRS, they do not share the same pixel alignment, resulting in pixels that do not align correctly:
![image](https://user-images.githubusercontent.com/17680388/180369660-b3139abb-04a4-4489-adb7-264c4920f9f7.png)

I would like to be able to "snap" `lowres_geobox2` to the pixel alignment of `lowres_geobox1`, so that both of my low resolution grids align perfectly:
![image](https://user-images.githubusercontent.com/17680388/180369729-cf8b44f9-3355-497a-8e88-4e84a1984645.png)

Snapping is currently supported when creating a new GeoBox directly (e.g. via `GeoBox.from_bbox`), however it would be useful to have a GeoBox method that would allow a user to perform snapping on existing GeoBoxes as well.

**Comment by robbibt** [comment]
Unsnapped and snapped grids:
![image](https://user-images.githubusercontent.com/17680388/180369030-164213c6-61a8-485e-8cd3-66784d5c03b1.png)

![image](https://user-images.githubusercontent.com/17680388/180369065-0d2aa11d-8d8e-40a4-8626-d77aa5e7cfea.png)

**Comment by Kirill888** [comment]
Probably also worth adding `snap=False|True` to `zoom_out` method, aligning two arbitrary geoboxes with compatible reprojections/resolution  to each other is somewhat more involved (but not a lot more) than snapping to pixel size.

Maybe also worth supporting alignment between geoboxes of different resolutions when pixel sizes are related via exact integer scale `1x1 == 3x3`.
