### ISSUE TITLE
0.3.1 broke compatibility with Python 3.10

### ISSUE THREAD

**Issue by fwfichtner** [opendatacube/odc-geo#73]
This is somewhat confusing, but I think Python 3.10 deprecated classes that are generic within collections (Collections Abstract Base Classes): https://docs.python.org/3/whatsnew/3.10.html#collections-abc. 

That means 2b32ed6bca5949dcee313f5b965ee15e5a7d0e88 and your latest release results in the following error when using Python 3.10:

```
...
File "/usr/local/lib/python3.10/site-packages/odc/geo/crs.py", line 53, in _make_crs_key
    if isinstance(crs_spec, collections.Hashable):
AttributeError: module 'collections' has no attribute 'Hashable'
```

**Comment by snowman2** [comment]
Proposed fix in #74
