### ISSUE TITLE
"name" param from `.odc.add_to()` not working as expected

### ISSUE THREAD

**Issue by robbibt** [opendatacube/odc-geo#99]
**Expected result**
The `.odc.add_to()` method has a "name" parameter that I expected would be used to name output layers in the `LayerControl` widget of a Folium map. For example:
```
import folium
m = folium.Map(control_scale=True)
ds.elevation.odc.add_to(m, name="elevation")
ds.elevation_uncertainty.odc.add_to(m, name="elevation_uncertainty")

# Zoom map
m.fit_bounds(ds.odc.map_bounds())
folium.LayerControl().add_to(m)
display(m)
```

**Actual result**
Layers in the `LayerControl` dropdown are instead named "macro_element". This makes it difficult to properly visualise layers using `odc.geo`.
![image](https://github.com/opendatacube/odc-geo/assets/17680388/9b3d3401-ef44-47e6-8110-0204eeb94a3a)

odc-geo version: '0.4.0'
Foium version: '0.14.0'

**Comment by robbibt** [comment]
Looks like I can do it like this by manually overwriting the layer names. But it'd be neat to be able to do it directly via the existing `name=` param!
```
import folium
m = folium.Map(control_scale=True)
layer1 = ds.elevation.odc.add_to(m)
layer1.layer_name = "elevation"
layer2 = ds.elevation_uncertainty.odc.add_to(m)
layer2.layer_name = "elevation_uncertainty"

# Zoom map
m.fit_bounds(ds.odc.map_bounds())
folium.LayerControl().add_to(m)
display(m)
```

![image](https://github.com/opendatacube/odc-geo/assets/17680388/07f70cfc-3834-497e-a5f5-9959b4a68127)

**Comment by Kirill888** [comment]
@robbibt thanks for report, want to try fixing it in here:

https://github.com/opendatacube/odc-geo/blob/d5e88d56dafebdd55fd91db810670593d2a7fb49/odc/geo/_map.py#L13-L22
